geekshop-main3/geekshop-main/geekshop/urls.py
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import mainapp.views as mainapp
from django.conf import settings

# from mainapp.models import Category


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main, name='main'),
    path("products/", include("mainapp.urls", namespace="products")),
    path('contact/', mainapp.contact, name='contact'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop-main3/geekshop-main/mainapp/urls.py
from django.urls import path

# import views as mainapp
import mainapp.views as mainapp

app_name = 'mainapp'
urlpatterns = [
    path('', mainapp.products, name='products'),
    path('<slug:slug>/', mainapp.products, name='category'),
    path('<slug:category>/<slug:product>/', mainapp.product_detail, name='product')
]

geekshop-main3/geekshop-main/mainapp/models.py
from django.db import models
from django.db.models.signals import pre_save
# Create your models here.
from pytils import translit


class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название', unique=True)
    description = models.TextField(blank=True, verbose_name='Описание', default='Здесь должно быть описание...')
    slug = models.SlugField(max_length=70, unique=True)

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'

    def __str__(self):
        return self.title


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    title = models.CharField(max_length=255, verbose_name='Название')
    image = models.ImageField(blank=True, upload_to='media', )
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    old_price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name='Старая цена')
    description = models.TextField(default='Описание товара...', verbose_name='Описание', blank=True)
    short_desc = models.CharField(max_length=255, blank=True, default='Короткое описание',
                                  verbose_name='Короткое описание')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    is_stock = models.BooleanField(default=True, verbose_name='На складе')
    slug = models.SlugField(max_length=70, unique=True, blank=False)

    class Meta:
        verbose_name_plural = 'Товары'
        verbose_name = 'Товар'

    def __str__(self):
        return self.title


def slug_generator(sender, instance, *args, **kwargs):
    if not instance.slug:
        if sender.objects.count():
            instance.slug = translit.slugify(instance.title + '-' + str(sender.objects.order_by('-pk')[0].pk + 1))
        else:
            instance.slug = translit.slugify(instance.title + '-' + '1')


pre_save.connect(slug_generator, sender=Product)
pre_save.connect(slug_generator, sender=Category)


class ImageGallery(models.Model):
    image = models.ImageField(blank=True, upload_to='media')
    product = models.ForeignKey(Product, default=None, blank=True, related_name='images', on_delete=models.PROTECT)


class Contact(models.Model):
    phone = models.CharField(max_length=20, unique=True, verbose_name='Телефон')
    email = models.CharField(max_length=255, verbose_name='Эл. почта')
    city = models.CharField(max_length=255, verbose_name='Город')
    address = models.CharField(max_length=255, verbose_name='Адрес')

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return self.city

geekshop-main3/geekshop-main/mainapp/views.py
from django.shortcuts import render

from .models import Product, Category, Contact


def main(request):
    title = 'главная'
    context = {
        'title': title,
        'products': Product.objects.all().order_by('?')[:4],
    }
    return render(request, 'mainapp/index.html', context=context)


def products(request, slug=None):
    title = 'продукты'
    context = {
        'menu_links': Category.objects.all(),
        'products': Product.objects.all(),
        'title': title,
        'rel_products': Product.objects.all().order_by('?')[:3],
    }

    return render(request, 'mainapp/products.html', context=context)


def contact(request):
    title = 'контакты и т.д.'
    context = {
        'title': title,
        'contacts': Contact.objects.all()
    }

    return render(request, 'mainapp/contact.html', context=context)


def product_detail(request, category, product):
    product = Product.objects.get(slug=product)
    context = {
        'title': product.title,
        'product': product,
        'menu_links': Category.objects.all(),
        'rel_products': Product.objects.all().order_by('?')[:3],
    }
    return render(request, 'mainapp/product_detail.html', context=context)

geekshop-main3/geekshop-main/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title| capfirst }}
        {% endblock title %}
    </title>
    {% block css %}
        <link href="{% static 'style.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fonts/font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    {% endblock %}
    {% block js %}

    {% endblock %}
</head>
<body>
<div class="container">
    {% block menu %}

    {% endblock menu %}

    {% block content %}

    {% endblock content %}
</div>

{% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input name="email" placeholder="ваш email" type="email">
                    <a href="#"><i aria-hidden="true" class="fa fa-paper-plane fa-2x"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB 2017</p>
        <div class="social">
            <a class="social1" href="#"></a>
            <a class="social2" href="#"></a>
            <a class="social3" href="#"></a>
            <a class="social4" href="#"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock footer %}

</body>

</html>

geekshop-main3/geekshop-main/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    <div class="hero">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_menu.html' %}
        </div>
        <h1>наши контакты</h1>
    </div>
{% endblock menu %}

{% block content %}
    <div class="location">
        {% for contact in contacts %}
            <div class="location-1">
                <i class="fa fa-map-marker fa-3x"></i>
                <h4>{{ contact.city }}</h4>
                <div class="contacts">
                    <h5>Телефон</h5>
                    <p>{{ contact.phone }}</p>
                </div>
                <div class="contacts">
                    <h5>Email</h5>
                    <p>{{ contact.email }}</p>
                </div>
                <div class="contacts">
                    <h5>Адрес</h5>
                    <p>{{ contact.address }}</p>
                </div>
            </div>
        {% endfor %}

    </div>

    <div class="clr"></div>

{% endblock content %}

geekshop-main3/geekshop-main/mainapp/templates/mainapp/includes/inc_menu.html
<a class="logo" href="{% url 'main' %}"></a>
<ul class="menu">
    <li><a class="{% if request.resolver_match.url_name == 'main' %}active{% endif %}" href="{% url 'main' %}">домой</a>
    </li>
    <li><a class="{% if 'products' in request.path %}active{% endif %}"
           href="{% url 'products:products' %}">продукты</a></li>
    <li><a class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}" href="{% url 'contact' %}">контакты</a>
    </li>
</ul>
<a class="search" href="#"></a>
<a class="basket" href="#"></a>

geekshop-main3/geekshop-main/mainapp/templates/mainapp/includes/inc_product_menu.html
<ul class="links-menu">
    <li>
        <a class="{% if request.resolver_match.url_name == 'products' %}active{% endif %}"
           href="{% url 'products:products' %}">все</a>
    </li>
    {% for link in menu_links %}
        <li>
            <a class="{% if '/products/'|add:link.slug|add:'/' in request.path  %}active{% endif %}"
               href="{% url 'products:category' link.slug %}">{{ link.title }}</a>
        </li>
    {% endfor %}

</ul>

geekshop-main3/geekshop-main/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block menu %}
    <div class="slider">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_menu.html' %}
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a class="button-order" href="#">заказать <img alt="" src="{% static 'img/arrow.png' %}"></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
{% endblock menu %}

{% block content %}
    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img alt="" src="{% static 'img/arrow.png' %}"></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for product in products %}
                <div class="block">
                    <a href="{% url 'products:product' product.category.slug product.slug  %}">
                        <img alt="img" src="{{ product.image.url }}" style="height: 270px; width: 270px;">
                        <div class="text">
                            <img src="{% static 'img/icon-hover.png' %}" alt="img">
                            <h4>{{ product.title }}</h4>
                            <p>{{ product.description|truncatewords:8}}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}

        </div>
    </div>

    <div class="clr"></div>
{% endblock content %}

geekshop-main3/geekshop-main/mainapp/templates/mainapp/product_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_menu.html' %}
        </div>
    </div>
{% endblock menu %}

{% block content %}

    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_product_menu.html' %}
        </div>


        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{{ product.image.url }}" style="width: 570px;height: 570px;">
                </div>
                <div class="slider-control">
                    {% for image in product.images.all %}
                        <div class="block">
                            <a href="#"><img alt="" src="{{ image.image.url }}">
                                <div class="text"></div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.title }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a class="red-button" href="#">
                    заказать <i aria-hidden="true" class="fa fa-chevron-right"></i>
                </a>
                <div class="description-text">
                    <p>Расположитесь комфортно.</p>
                    <p>Отличное качество материалов
                        позволит вам это.</p>
                    <p>Различные цвета</p>
                    <p>высочайший уровень
                        эргономики и прочность.</p>
                </div>
            </div>
        </div>


        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img alt="" src="{% static 'img/arrow.png' %}"></a>
            </div>
            <div class="related-products clearfix">
                {% for product in rel_products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.category.slug product.slug %}"><img alt=""
                                                                                                       src="{{ product.image.url }}"
                                                                                                       style="width: 370px;height: 370px;">
                            <div class="text">
                                <img alt="img" src="{% static 'img/icon-hover.png' %}">
                                <h4>{{ product.title }}</h4>
                                <p>{{ product.description|truncatewords:2 }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>
{% endblock content %}

geekshop-main3/geekshop-main/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}


{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_menu.html' %}
        </div>
    </div>
{% endblock menu %}

{% block content %}

    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/includes/inc_product_menu.html' %}
        </div>
        {% for product in products %}
            {% if product.category.slug in request.path or request.path == '/products/' %}
                <a href="{% url 'products:product' product.category.slug product.slug %}">
                    <div class="details-products">
                        <div class="details-slider">
                            <div class="slider-product">
                                <img src="{{ product.image.url }}" style="width: 570px;height: 570px;">
                            </div>
                            <div class="slider-control">
                                {% for image in product.images.all %}
                                    <div class="block">
                                        <a href="#"><img alt="" src="{{ image.image.url }}">
                                            <div class="text"></div>
                                        </a>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="description">
                            <h3 class="big-bold">{{ product.title }}</h3>
                            <h3 class="red">горячее предложение</h3>
                            <p class="price"> {{ product.price }} <span>руб</span></p>
                            <a class="red-button" href="#">
                                заказать <i aria-hidden="true" class="fa fa-chevron-right"></i>
                            </a>
                            <div class="description-text">
                                <p>Расположитесь комфортно.</p>
                                <p>Отличное качество материалов
                                    позволит вам это.</p>
                                <p>Различные цвета</p>
                                <p>высочайший уровень
                                    эргономики и прочность.</p>
                            </div>
                        </div>
                    </div>
                </a>
            {% endif %}

        {% endfor %}


        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img alt="" src="{% static 'img/arrow.png' %}"></a>
            </div>
            <div class="related-products clearfix">
                {% for product in rel_products %}
                    <div class="block">
                        <a href="{% url 'products:product' product.category.slug product.slug %}"><img alt=""
                                                                                                       src="{{ product.image.url }}"
                                                                                                       style="width: 370px;height: 370px;">
                            <div class="text">
                                <img alt="img" src="{% static 'img/icon-hover.png' %}">
                                <h4>{{ product.title }}</h4>
                                <p>{{ product.description|truncatewords:2 }} </p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>
{% endblock content %}